### PR TITLE
Enhancement: allow usage of existing kms key for node storage encryption

### PR DESCRIPTION
**Pull request by k11h-de**
Hi iits Team,

I'd like to suggest following enhancement. We have a shared responsibility approach. So we need to use an existing kms key for node pool storage encryption.

This PR adds an optional variable `node_storage_encryption_kms_key_name` that can be used for encryption, without the need for the cce module to create a dedicated kms key. 

I tested the backward-compatibility successfully.

### CODE REVIEW

**Comment by victorgetz** [comment]
@canaykin

**Comment by canaykin** [comment]
Hi Karsten!

This is a nice improvement, but if we are adding this, I would love to add it to all modules that support KMS encryption instead of just CCE. 

I will discuss it with @PhilipSiemerIITS to determine how long it would take to implement, and try to ship it with the next release.

Best,
Can.

**Comment by k11h-de** [comment]
@canaykin 
I added the same functionality to the `rds` and `jumphost` module. I have not tested these changes, but I am quite confident they're fine, as the logic is exactly the same. 

Cheers Karsten

**Comment by canaykin** [comment]
@k11h-de ok now you are making my job way too easy man. We'll test them and ship them with next release.

**Pull request merged**
